---
title: "Clustering_Code"
output: html_document
date: "2026-03-17"
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
`%nin%` <- Negate(`%in%`)
library(tidyverse); library(magrittr); library(plotly)
library(compositions); library(VIM); library(dplyr)
library(MAI); library(ClusterR); library(RVA)
library(ggrepel); library(NbClust); library(sva)
library(ggplot2); library(ggalluvial); library(reshape2)

source(here::here("Code", "Simulation_Functions.R"))
# source(here::here("Code", "CleanAllTimePoints_Ezra.R"))
# 
# dat_mb_T1 <- read.csv(here::here("DataProcessed", "CF_clean_T1_mb.csv"))
# dat_pt_T1 <- read.csv(here::here("DataProcessed", "CF_clean_T1_pt.csv"))
```

Data Cleaning with updated datasets
```{r}
dat_mb <- read.csv(here::here("DataProcessed", "micro.csv"), header = TRUE)
dat_pt <- read.csv(here::here("DataProcessed", "soma.csv"), header = TRUE)

## Microbiome ------------------------------------------------------------------

dat_mb_wide <- dat_mb %>%
  dplyr::select(sid, OTU_Name, seq_count) %>%
  tidyr::pivot_wider(
    names_from = OTU_Name,
    values_from = seq_count#,
    #values_fn = max
  ) # Convert to wide

# > dim(dat_mb)
# [1] 2263   46
# > dim(dat_mb_wide)
# [1] 31 74
# > length(unique(dat_mb$sid))
# [1] 31
# > length(unique(dat_mb$OTU_Name))
# [1] 73

tots_new <- rowSums(dat_mb_wide[,-1])
  # Sequencing depth

dat_mb_clr <- sweep(dat_mb_wide[,-1], 1, 1/tots_new, "+") %>%
  apply(1, clr) %>%
  t() # CLR transform with pseudocount

batch <- floor((dat_mb_wide$sid - 1) / 25) + 1
  # Create batch variable

mb_mat <- t(dat_mb_clr)
  # Adjust format

mb_corrected <- ComBat(
  dat = mb_mat,
  batch = batch,
  par.prior = TRUE,
  prior.plots = FALSE
) # Batch correction

mb_corrected <- t(mb_corrected)
  # Return to original format

dat_mb_T1 <- data.frame(cbind(sid = dat_mb_wide$sid, mb_corrected))
  # Add sid back

## Proteomics ------------------------------------------------------------------

dat_pt_wide <- dat_pt %>%
  dplyr::select(sid, somaid2, lmeas) %>%
  tidyr::pivot_wider(
    names_from = somaid2,
    values_from = lmeas#,
    #values_fn = max
  ) # Convert to wide

# > dim(dat_pt)
# [1] 120714     15
# > dim(dat_pt_wide)
# [1]   31 3895
# > length(unique(dat_pt$sid))
# [1] 31
# > length(unique(dat_pt$somaid2))
# [1] 3894

batch <- floor((dat_pt_wide$sid - 1) / 25) + 1
  # Create batch variable

prot_mat <- t(dat_pt_wide[,-1])
  # Adjust format

prot_corrected <- ComBat(
  dat = prot_mat,
  batch = batch,
  par.prior = TRUE,
  prior.plots = FALSE
) # Batch correction

prot_corrected <- t(prot_corrected)
  # Return to original format

dat_pt_T1 <- data.frame(sid = dat_pt_wide$sid, prot_corrected)
  # Add sid back

# write.csv(dat_mb_T1, here::here("DataProcessed", "micro_wide_Ezra.csv"))
# write.csv(dat_pt_T1, here::here("DataProcessed", "soma_wide_Ezra.csv"))


dat_clin <- read.csv(here::here("DataRaw", "CF_pex_clinical.txt"))
dat_clin <- dat_clin %>%
  filter(sid %in% dat_mb_T1$sid)
```


Individual Clustering
```{r}
rownames(dat_mb_T1) <- dat_mb_T1$sid
rownames(dat_pt_T1) <- dat_pt_T1$sid
dat_mb_T1 <- dat_mb_T1[, !(names(dat_mb_T1) %in% c("X", "sid"))]
dat_pt_T1 <- dat_pt_T1[, !(names(dat_pt_T1) %in% c("X", "sid"))]

mb_LapSft <- gaussLaplac(dat_mb_T1, lap.type = 'shift', 
                         kernel = "Spectrum")
  #Microbiome Eigenvalues of graph Laplacian and Heatmap of Adjacency Matrix for T1 
prot_LapSft <- gaussLaplac(dat_pt_T1, lap.type = 'shift',
                        kernel = "Spectrum")
  #Proteomics Eigenvalues of graph Laplacian and Heatmap of Adjacency Matrix for T1 
```

Joint Clustering via Spectral Clustering and Flag Mean
```{r}
mb_eigSft <- eigen(mb_LapSft)
prot_eigSft <- eigen(prot_LapSft)

# Spectral Clustering -----------------------------------------------------

mb_vecs <- mb_eigSft$vectors

mb_for_nb <- mb_vecs[, 1:5]   
  # first 5 eigenvectors
NbClust(mb_for_nb, distance = "euclidean", method = "kmeans", index = "alllong")
  # TraceW gives 4, TrCovW gives 3
mk <- 3
mbInd <- 1:mk
mbv <- mb_vecs[,mbInd]
mbGMM <- GMM(mbv, mk, dist_mode = 'eucl_dist', em_iter = 15)
mbClust <- predict(mbGMM, newdata = mbv)
  # 4 4 4 4 2 4 4 4 4 2 2 4 3 1 1 3 1 1 1 3 1 1 2 3 3 1 3 1 2 3 3

prot_vecs <- prot_eigSft$vectors
prot_for_nb <- prot_vecs[, 1:5]
NbClust(prot_for_nb, distance = "euclidean", method = "kmeans", index = "alllong")
  # TraceW gives 6, TrCovW gives 3
pk <- 3
protInd <- 1:pk
pev <- prot_eigSft$vectors[,protInd] 
set.seed(10)
protClust <- kmeans(pev, pk, nstart=5)$cluster

# Flag Mean ----------------------------------------------------------------

Up <- prot_eigSft$vectors[, protInd]
Um <- mb_eigSft$vectors[,mbInd]

flm <- flmSym <- flagMean(list(Up, Um), plots = FALSE)
flm.vecs <- flm$u

NbClust(flm.vecs, method = 'kmeans', index='alllong')
  # If pt is 3: TraceW gives 4, TrCovW gives 4
Fk <- 4
set.seed(235)
flgClust <- kmeans(flm.vecs[,1:4], centers = Fk, nstart = 10)$cluster

flm.vecs %>% as.data.frame %>% 
  mutate(clust = factor(flgClust)) %>% 
  plot_ly(x = ~V2, y = ~V3, z = ~V4, 
          color = ~clust, colors='Set1') %>%
  add_markers()
```

```{r warning=FALSE}
dat_cluster <- data.frame(sid = rownames(dat_mb_T1), 
                          joint = flgClust, mb = mbClust, pt = protClust,
                          stringsAsFactors = FALSE)

freqDF <- as.data.frame(
  xtabs(~ joint + mb + pt,
        data = dat_cluster)
  ) %>%
  rename(
    `Joint Clusters` = joint,
    `Microbiome Clusters` = mb,
    `Proteomics Clusters` = pt
  )

ggplot(
  freqDF,
  aes(
    axis1 = `Microbiome Clusters`,
    axis2 = `Proteomics Clusters`,
    y = Freq
  )
) +
  geom_alluvium(aes(fill = `Joint Clusters`), alpha = 0.8) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_x_discrete(
    limits = c("Microbiome Clusters", "Proteomics Clusters"),
    expand = c(.1, .1)
  ) +
  labs(
    y = "Number of Individuals",
    title = "Individual Cluster Comparison"
  ) +
  theme_minimal()
```

```{r}
cluster_microbiome <- function(mk){
  mb_vecs <- mb_eigSft$vectors
  mbInd <- 1:mk
  mbv <- mb_vecs[,mbInd]
  mbGMM <- GMM(mbv, mk, dist_mode = 'eucl_dist', em_iter = 15)
  mbClust <- predict(mbGMM, newdata = mbv)
}
cluster_proteomics <- function(pk){
  prot_vecs <- prot_eigSft$vectors
  protInd <- 1:pk
  pev <- prot_eigSft$vectors[,protInd] 
  set.seed(10)
  protClust <- kmeans(pev, pk, nstart=5)$cluster
}

# Microbiome clusters
mbClust3 <- cluster_microbiome(3)
mbClust4 <- cluster_microbiome(4)
mbClust5 <- cluster_microbiome(5)

# Proteomics clusters
protClust3 <- cluster_proteomics(3)
protClust4 <- cluster_proteomics(4)
protClust5 <- cluster_proteomics(5)

alluvial_df <- data.frame(
    sid = rownames(dat_mb_T1),
    joint = factor(flgClust),
    mb3 = mbClust3,
    mb4 = mbClust4,
    mb5 = mbClust5,
    pt3 = protClust3,
    pt4 = protClust4,
    pt5 = protClust5,
    stringsAsFactors = FALSE
  ) %>%
  pivot_longer(
    cols = c(mb5, mb4, mb3, pt3, pt4, pt5),
    names_to = "axis",
    values_to = "cluster"
  ) %>%
  mutate(
    axis = factor(axis, levels = c("mb5","mb4","mb3","pt3","pt4","pt5"))
  ) 

ggplot(
  alluvial_df,
  aes(
    x = axis,
    stratum = cluster,
    alluvium = sid,
  )
) +
  geom_flow(aes(fill = joint), alpha = 0.6) +
  geom_stratum(fill = "white", color = "black") +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_x_discrete(
    labels = c(
      "mb5" = "Microbiome (5)",
      "mb4" = "Microbiome (4)",
      "mb3" = "Microbiome (3)",
      "pt3" = "Proteomics (3)",
      "pt4" = "Proteomics (4)",
      "pt5" = "Proteomics (5)"
    )
  ) +
  labs(
    title = "Joint Cluster Comparison Across All Microbiome and Proteomics Cluster Solutions",
    y = "Number of Individuals",
    fill = "Joint Cluster",
    x = ""
  ) +
  theme_minimal()
```


```{r warning=FALSE}
clusters <- sapply(2:6, function(K){
  set.seed(4)
  kmeans(flm.vecs[, 1:4], centers = K, nstart = 10)$cluster
})

clusters <- as.data.frame(clusters)
names(clusters) <- paste0("C", 2:6)
clusters$dummy <- 1

freqDF <- as.data.frame(
  ftable(xtabs(~ C6 + C5 + C4 + C3 + C2 + dummy, data = clusters))
  ) %>%
  rename(
    `2 Clusters` = C2,
    `3 Clusters` = C3,
    `4 Clusters` = C4,
    `5 Clusters` = C5,
    `6 Clusters` = C6
  )

ggplot(
  freqDF,
  aes(
    axis1 = `2 Clusters`,
    axis2 = `3 Clusters`,
    axis3 = `4 Clusters`,
    axis4 = `5 Clusters`,
    y = Freq
  )
) +
  geom_alluvium(aes(fill = `6 Clusters`), alpha = 0.8) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_x_discrete(
    limits = c("2 Clusters", "3 Clusters", "4 Clusters", "5 Clusters"),
    expand = c(.1, .1)
  ) +
  labs(
    y = "Number of Individuals",
    fill = "6 Clusters",
    title = "Joint Cluster Comparison"
  ) +
  theme_minimal()

# ggplot(freqDF,
#        aes(axis1 = C3, axis2 = C4, axis3 = C5, axis4 = C6, y = Freq)) +
#   geom_alluvium(aes(fill = C2)) +
#   geom_stratum() +
#   geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
#   theme_minimal()
```
```{r}
sig_bac_prot <- data.frame(cbind(flgClust, dat_pt_T1$SOMA_1809, dat_pt_T1$SOMA_2100, dat_pt_T1$SOMA_2524, dat_pt_T1$SOMA_2331, dat_pt_T1$SOMA_2738, dat_pt_T1$SOMA_2102, dat_pt_T1$SOMA_2801, dat_pt_T1$SOMA_2067, dat_pt_T1$SOMA_3338, dat_pt_T1$SOMA_2789, #dat_pt_T1$SOMA_3119,
                                 dat_pt_T1$SOMA_2095, dat_pt_T1$SOMA_1985))
colnames(sig_bac_prot) <- c("Group", "Elastase", "IL-6", "IL-8", "IL-1b", "MMP-2", "MMP-9", "SLPI", "TIMP-1", "TNF-a", "CRP", #"calgranulin B",
                            "HMG-1", "IFN-g")
df.m <- melt(sig_bac_prot, id.var = "Group")

p <- ggplot(data = df.m, aes(x=variable, y=value)) +
             geom_boxplot(aes(fill=factor(Group)))
p <- p + xlab("Protein") + ylab("log2(RFU)") + ggtitle("Difference in Clinically Relevant Protein Amounts by Group")
p <- p + guides(fill=guide_legend(title="Cluster"))
p + facet_wrap( ~ variable, scales="free")
```

```{r}
tots <- rowSums(dat_mb_wide[,-1], na.rm = TRUE)
  # Sequencing depth
dat_mb_ra <- sweep(dat_mb_wide[,-1], 1, tots, FUN = "/")
  # Relative abundance matrix
dat_mb_ra <- data.frame(sid = dat_mb_wide$sid, cluster = flgClust, dat_mb_ra)
  # Add sid and group
mean_ra <- colMeans(dat_mb_ra[, !(names(dat_mb_ra) %in% c("sid", "cluster"))], 
                    na.rm = TRUE)  
  # Compute mean ra for each taxa

### 1. Identify top 10 taxa
top10_taxa <- names(sort(mean_ra, decreasing = TRUE))[1:10]

### 2. Automatically detect the Pseudomonas column
pseudomonas_full <- grep("Pseudomonas$", colnames(dat_mb_ra), value = TRUE)

### 3. Compute Pseudomonas rank
pseudomonas_rank <- match(pseudomonas_full, names(sort(mean_ra, decreasing = TRUE)))

### 4. Combine taxa
top10_plus_pseudo <- unique(c(top10_taxa, pseudomonas_full))

### 5. Split taxonomy into components
split_taxa <- strsplit(top10_plus_pseudo, "[./]")

### 6. Extract short names (last element)
short_names <- sapply(split_taxa, function(x) x[length(x)])

### 7. Identify duplicates
dups <- names(which(table(short_names) > 1))

### 8. Function to find deepest differing level
deepest_difference <- function(parts_list) {
  max_len <- max(sapply(parts_list, length))
  padded <- t(sapply(parts_list, function(x) c(rep(NA, max_len - length(x)), x)))
  diff_cols <- apply(padded, 2, function(col) length(unique(col)) > 1)
  last_diff <- max(which(diff_cols))
  sapply(seq_len(nrow(padded)), function(i) padded[i, last_diff])
}

### 9. Build final labels
final_labels <- short_names

for (dup in dups) {
  idx <- which(short_names == dup)
  differing_parts <- deepest_difference(split_taxa[idx])
  final_labels[idx] <- paste0(short_names[idx], " (", differing_parts, ")")
}

names(final_labels) <- top10_plus_pseudo

### 10. Melt data and apply labels
dat_top10_long <- dat_mb_ra %>%
  dplyr::select(sid, cluster, all_of(top10_plus_pseudo)) %>%
  reshape2::melt(id.vars = c("sid", "cluster"),
                 variable.name = "taxa",
                 value.name = "rel_abundance")

# Add line break before parenthetical part for long labels
final_labels <- gsub(" \\(", "\n(", final_labels)
names(final_labels) <- names(final_labels)

dat_top10_long$taxa <- final_labels[dat_top10_long$taxa]

### Reorder taxa by abundance (mean_ra)
# Extract mean abundance for the taxa in the plot
abund_order <- mean_ra[top10_plus_pseudo]

# Reorder using the final labels
ordered_labels <- final_labels[order(abund_order, decreasing = TRUE)]

# Apply factor ordering
dat_top10_long$taxa <- factor(dat_top10_long$taxa,
                              levels = ordered_labels)

### 11. Plot with automatic Pseudomonas rank in title
p <- ggplot(dat_top10_long, aes(x = taxa, y = rel_abundance)) +
  geom_boxplot(aes(fill = factor(cluster))) +
  xlab("Bacterial Taxa") +
  ylab("Relative Abundance") +
  ggtitle(paste0("Top 10 Most Abundant Bacteria + Pseudomonas (Rank ", pseudomonas_rank, ")")) +
  guides(fill = guide_legend(title = "Cluster")) +
  facet_wrap(~ taxa, scales = "free")

p
```

```{r}
library(dplyr)
library(purrr)
library(broom)
library(stringr)

# ------------------------------------------------------------
# 1. Function: run univariate ANOVAs with FDR correction
# ------------------------------------------------------------
run_univariate_anovas <- function(data, group_var, vars = NULL, fdr_cutoff = 0.05) {
  group_var <- rlang::ensym(group_var)

  # If no variable list provided, test all numeric variables except the group
  if (is.null(vars)) {
    vars <- data %>%
      select(where(is.numeric), -!!group_var) %>%
      names()
  }

  results <- map_dfr(vars, function(v) {
    formula <- as.formula(paste(v, "~", rlang::as_string(group_var)))

    p <- aov(formula, data = data) %>%
      tidy() %>%
      filter(term != "Residual") %>%
      slice(1) %>%
      pull(p.value)

    tibble(variable = v, p.value = p)
  })

  results <- results %>%
    mutate(p_adj = p.adjust(p.value, method = "fdr")) %>%
    arrange(p_adj)

  list(
    significant = results %>% filter(p_adj < fdr_cutoff),
    all_results = results
  )
}

# ------------------------------------------------------------
# 2. Build cluster table with correct SID alignment
# ------------------------------------------------------------
groups <- tibble(
  sid = as.numeric(rownames(dat_mb_T1)),
  joint = flgClust,
  mb = mbClust,
  pt = protClust
)

# ------------------------------------------------------------
# 3. Align datasets by SID and join cleanly
# ------------------------------------------------------------
dat_clin <- dat_clin %>%
  filter(sid %in% groups$sid) %>%      # keep only matched subjects
  arrange(sid) %>%                     # enforce consistent ordering
  inner_join(groups %>% arrange(sid),  # join cluster assignments
             by = "sid") %>%
  mutate(
    # genotype count
    genotype_F508del = str_count(paste(genotypes1, genotypes2), "F508del"),

    # NEW difference variables (statistically sound)
    fev1_2v1 = tp2_fev1_pred - tp1_fev1_pred,
    fev1_3v1 = tp3_fev1_pred - tp1_fev1_pred,
    fvc_2v1 = tp2_fvc_pred - tp1_fvc_pred,
    fvc_3v1 = tp3_fvc_pred - tp1_fvc_pred,
    pes_2v1 = tp2_pes_total - tp1_pes_total,
    pes_3v1 = tp3_pes_total - tp1_pes_total
  )

# ------------------------------------------------------------
# 4. Variables to test
# ------------------------------------------------------------
clin_vars <- c(
  "gender", "age", "genotype_F508del", "tp1_pe_pastyr", 
  "tp1_hosp_pastyr", "tp1_height", "tp1_weight",
  "tp1_fev1_pred", "tp2_fev1_pred", "tp3_fev1_pred",
  "fev1_2v1", "fev1_3v1",
  "tp1_fvc_pred", "tp2_fvc_pred", "tp3_fvc_pred",
  "fvc_2v1", "fvc_3v1",
  "tp1_pes_total", "tp2_pes_total", "tp3_pes_total",
  "pes_2v1", "pes_3v1", 
)

# ------------------------------------------------------------
# 5. Run ANOVAs
# ------------------------------------------------------------
clin_anova <- run_univariate_anovas(dat_clin, group_var = joint, vars = clin_vars)

clin_anova$all_results

dat_mb_T1$sid <- groups$sid
dat_mb_T1$joint <- groups$joint
micro_anova <- run_univariate_anovas(dat_mb_T1, group_var = joint, vars = setdiff(colnames(dat_mb_T1), c("sid", "joint")))
micro_anova$significant

dat_pt_T1$sid <- groups$sid
dat_pt_T1$joint <- groups$joint
soma_anova <- run_univariate_anovas(dat_pt_T1, group_var = joint, vars = setdiff(colnames(dat_pt_T1), c("sid", "joint")))
head(soma_anova$all_results, 20)
```

```{r}
  # Select statistically significant taxa
### --- 0. Compute relative abundance matrix ---
tots <- rowSums(dat_mb_wide[,-1], na.rm = TRUE)
dat_mb_ra <- sweep(dat_mb_wide[,-1], 1, tots, FUN = "/")
dat_mb_ra <- data.frame(sid = dat_mb_wide$sid, cluster = flgClust, dat_mb_ra)

mean_ra <- colMeans(dat_mb_ra[, !(names(dat_mb_ra) %in% c("sid", "cluster"))],
                    na.rm = TRUE)

### --- 1. Select statistically significant taxa ---
sig_taxa <- micro_anova$significant$variable
# sig_taxa <- sig_taxa[sig_taxa %in% colnames(dat_mb_ra)]

### --- 2. Split taxonomy and create short names ---
split_taxa <- strsplit(sig_taxa, "[./]")
short_names <- sapply(split_taxa, function(x) x[length(x)])

### --- 3. Identify duplicates and resolve deeper taxonomy ---
dups <- names(which(table(short_names) > 1))

deepest_difference <- function(parts_list) {
  max_len <- max(sapply(parts_list, length))
  padded <- t(sapply(parts_list, function(x) c(rep(NA, max_len - length(x)), x)))
  diff_cols <- apply(padded, 2, function(col) length(unique(col)) > 1)
  last_diff <- max(which(diff_cols))
  sapply(seq_len(nrow(padded)), function(i) padded[i, last_diff])
}

final_labels <- short_names
for (dup in dups) {
  idx <- which(short_names == dup)
  differing_parts <- deepest_difference(split_taxa[idx])
  final_labels[idx] <- paste0(short_names[idx], " (", differing_parts, ")")
}

names(final_labels) <- sig_taxa

### --- 4. Melt data for plotting ---
dat_sig_long <- dat_mb_ra %>%
  dplyr::select(sid, cluster, all_of(sig_taxa)) %>%
  reshape2::melt(id.vars = c("sid", "cluster"),
                 variable.name = "taxa",
                 value.name = "rel_abundance")

# Add line break before parentheses for readability
final_labels <- gsub(" \\(", "\n(", final_labels)

dat_sig_long$taxa <- final_labels[dat_sig_long$taxa]

### --- 5. Order taxa by mean abundance ---
abund_order <- mean_ra[sig_taxa]
ordered_labels <- final_labels[order(abund_order, decreasing = TRUE)]

dat_sig_long$taxa <- factor(dat_sig_long$taxa,
                            levels = ordered_labels)

### --- 6. Plot ---
p <- ggplot(dat_sig_long, aes(x = taxa, y = rel_abundance)) +
  geom_boxplot(aes(fill = factor(cluster))) +
  xlab("Bacterial Taxa") +
  ylab("Relative Abundance") +
  ggtitle(paste0("Statistically Significant Bacteria (FDR < 0.05, n = ",
                 length(sig_taxa), ")")) +
  guides(fill = guide_legend(title = "Cluster")) +
  facet_wrap(~ taxa, scales = "free")

p
```


```{r warning=FALSE}
diff_boxplot <- dat_clin %>%
  dplyr::select(
    joint,
    fev1_2v1,
    fev1_3v1,
    fvc_2v1,
    fvc_3v1
  ) %>%
  rename(
    group = joint,
    `FEV1 Time 2 - 1` = fev1_2v1,
    `FEV1 Time 3 - 1` = fev1_3v1,
    `FVC Time 2 - 1` = fvc_2v1,
    `FVC Time 3 - 1` = fvc_3v1
  ) %>%
  pivot_longer(
    cols = -group,
    names_to = "variable",
    values_to = "value"
  )

p <- ggplot(diff_boxplot, aes(x = variable, y = value)) +
  geom_boxplot(aes(fill = factor(group))) +
  labs(
    x = "Variable",
    y = "Difference",
    title = "Percent Predicted FEV1 and FVC Differences over Time by Group",
    fill = "Cluster"
  ) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 30, hjust = 1))

p
```
```{r}
table1::table1(~ gender + age + genotype_F508del + tp1_fev1_pred + tp2_fev1_pred + tp3_fev1_pred + tp1_fvc_pred + tp2_fvc_pred + tp3_fvc_pred + tp1_pes_total + tp2_pes_total + tp3_pes_total | joint, dat_clin)

dat_table1 <- dat_clin %>%
  mutate(
    joint = factor(joint, levels = sort(unique(joint)), labels = paste0("Cluster ", seq_len(Fk)))
  )  %>%
  rename(
    Gender = gender,
    `Age (years; TP1)` = age,
    `Number of F508del Alleles` = genotype_F508del,
    `FEV1 % Predicted (TP1)` = tp1_fev1_pred,
    `FEV1 % Predicted (TP2)` = tp2_fev1_pred,
    `FEV1 % Predicted (TP3)` = tp3_fev1_pred,
    `FVC % Predicted (TP1)` = tp1_fvc_pred,
    `FVC % Predicted (TP2)` = tp2_fvc_pred,
    `FVC % Predicted (TP3)` = tp3_fvc_pred,
    `PES Total (TP1)` = tp1_pes_total,
    `PES Total (TP2)` = tp2_pes_total,
    `PES Total (TP3)` = tp3_pes_total,
    `Pulmonary Exacerbations (Past Year; TP1)` = tp1_pe_pastyr, 
    `Hospitalizations (Past Year; TP1)` = tp1_hosp_pastyr, 
    `Height (cm; TP1)` = tp1_height, 
    `Weight (kg; TP1)` = tp1_weight
  )

table1::table1(
  ~ Gender + `Age (years; TP1)` + `Number of F508del Alleles` +
    `Height (cm; TP1)` + `Weight (kg; TP1)` + 
    `Pulmonary Exacerbations (Past Year; TP1)` + `Hospitalizations (Past Year; TP1)` +
    `FEV1 % Predicted (TP1)` + `FEV1 % Predicted (TP2)` + `FEV1 % Predicted (TP3)` +
    `FVC % Predicted (TP1)` + `FVC % Predicted (TP2)` + `FVC % Predicted (TP3)` +
    `PES Total (TP1)` + `PES Total (TP2)` + `PES Total (TP3)`
  | joint,
  data = dat_table1
)

table1::table1(
  ~ Gender + `Age (years; TP1)` + `Number of F508del Alleles` +
    `Height (cm; TP1)` + `Weight (kg; TP1)` + 
    `Pulmonary Exacerbations (Past Year; TP1)` + `Hospitalizations (Past Year; TP1)` +
    `FEV1 % Predicted (TP1)` + `FEV1 % Predicted (TP2)` + `FEV1 % Predicted (TP3)` +
    `FVC % Predicted (TP1)` + `FVC % Predicted (TP2)` + `FVC % Predicted (TP3)` +
    `PES Total (TP1)` + `PES Total (TP2)` + `PES Total (TP3)`,
  data = dat_table1
)
```

```{r}
# Missingness per variable
missing_by_group <- dat_clin %>%
  dplyr::select(all_of(c(clin_vars, "joint"))) %>%
  pivot_longer(cols = clin_vars, names_to = "variable", values_to = "value") %>%
  mutate(missing = is.na(value)) %>%
  group_by(variable, joint) %>%
  summarise(n_missing = sum(missing), .groups = "drop")
missing_by_group
fisher_missing <- dat_clin %>%
  pivot_longer(cols = clin_vars, names_to = "variable", values_to = "value") %>%
  mutate(missing = is.na(value)) %>%
  group_by(variable) %>%
  summarise(
    p_missing = {
      tab <- table(joint, missing)

      # Only run Fisher if table is at least 2x2
      if (nrow(tab) >= 2 && ncol(tab) >= 2) {
        fisher.test(tab)$p.value
      } else {
        NA_real_
      }
    },
    .groups = "drop"
  )
fisher_missing
  # Missingness does not appear to be associated with group
```
```{r}
# Check variance
library(car)
dat_clin$joint <- factor(dat_clin$joint)
levene_results <- map_dfr(clin_vars, function(v) {
  formula <- as.formula(paste(v, "~ joint"))
  p <- tryCatch(
    leveneTest(formula, data = dat_clin)[1, "Pr(>F)"],
    error = function(e) NA
  )
  tibble(variable = v, levene_p = p)
})
levene_results

dat_mb_T1$joint <- factor(dat_mb_T1$joint)
micro_vars <- setdiff(colnames(dat_mb_T1), c("sid", "joint"))
micro_vars <- micro_vars[sapply(dat_mb_T1[micro_vars], is.numeric)]
micro_levene <- map_dfr(micro_vars, function(v) {
  formula <- as.formula(paste(v, "~ joint"))
  p <- tryCatch(
    leveneTest(formula, data = dat_mb_T1)[1, "Pr(>F)"],
    error = function(e) NA_real_
  )
  tibble(variable = v, levene_p = p)
})
dat_pt_T1$joint <- factor(dat_pt_T1$joint)
soma_vars <- setdiff(colnames(dat_pt_T1), c("sid", "joint"))
soma_vars <- soma_vars[sapply(dat_pt_T1[soma_vars], is.numeric)]
soma_levene <- map_dfr(soma_vars, function(v) {
  formula <- as.formula(paste(v, "~ joint"))
  p <- tryCatch(
    leveneTest(formula, data = dat_pt_T1)[1, "Pr(>F)"],
    error = function(e) NA_real_
  )
  tibble(variable = v, levene_p = p)
})

micro_levene[micro_levene$variable %in% sig_taxa,]
```

